# Generated by Django 5.0.1 on 2024-01-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prod",
            fields=[
                ("prod_no", models.BigAutoField(primary_key=True, serialize=False)),
                ("prod_name", models.CharField(max_length=255)),
                ("prod_desc", models.TextField()),
                (
                    "prod_type",
                    models.CharField(
                        choices=[
                            ("T1", "Human Readable Type 1"),
                            ("T2", "Human Readable Type 2"),
                            ("T3", "Human Readable Type 3"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
                ("prod_img", models.ImageField(upload_to="images/")),
                ("prod_quantity", models.PositiveIntegerField(default=0)),
                (
                    "prod_status",
                    models.CharField(
                        choices=[("AC", "Active"), ("IA", "Inactive")],
                        default="AC",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
